/*
CREATE TABLE #T(ID INT, ITEMCODE VARCHAR(20), ITEMNAME VARCHAR(50),CATEGORY1 VARCHAR(50),
CATEGORY2 VARCHAR(50), CATEGORY3 VARCHAR(50), UNITPRICE FLOAT, 
TOTALAMOUNT INT, TOTALSALES FLOAT, COST FLOAT,INCOMEPERCENT FLOAT)
*/

DECLARE @ID AS INT
DECLARE CRS CURSOR FOR SELECT ID FROM ITEMS WHERE CATEGORY1='GIDA'
OPEN CRS
FETCH NEXT FROM CRS INTO @ID 
WHILE @@FETCH_STATUS=0
BEGIN
INSERT INTO #T EXEC GETITEMINCOME @ID
FETCH NEXT FROM CRS INTO @ID 
END
CLOSE CRS
DEALLOCATE CRS

SELECT AVG(INCOMEPERCENT)AVERAGEINCOME FROM #T

