/* 2022 yýlý ocak ayýndan verilen siparisleri detaylý sekilde ve 
tarihe göre sýralý sekilde getiriniz */

SELECT O.ID, O.DATE_ ,
I.ITEMCODE, I.ITEMNAME, I.BRAND, I.CATEGORY1, I.CATEGORY2, I.CATEGORY3,
OD.AMOUNT, OD.UNITPRICE, OD.LINETOTAL
FROM ORDERS O
JOIN ORDERDETAILS OD ON OD.ORDERID = O.ID
JOIN ITEMS I ON I.ID = OD.ITEMID
WHERE DATE_ BETWEEN '2022-01-01' AND '2022-01-31 23:59:59'
ORDER BY DATE_ DESC

--Nazmiye Ercan isimli kullanýcýnýn verdiði siparislerin detaylarýný  getiriniz.

SELECT U.NAMESURNAME, O.ID ORDER_NO ,O.DATE_ ORDER_DATE,
I.ITEMCODE, I.ITEMNAME, I.BRAND,
OD.AMOUNT, OD.UNITPRICE, OD.LINETOTAL
FROM ORDERS O
JOIN USERS U ON O.USERID = U.ID
JOIN ORDERDETAILS OD ON OD.ORDERID = O.ID
JOIN ITEMS I ON I.ID = OD.ITEMID
WHERE U.NAMESURNAME = 'Nazmiye Ercan'
ORDER BY ORDER_DATE

-- Her sehrin ilcelerini getiren sorguyu yazýnýz.

SELECT CT.CITY, T.TOWN 
FROM CITIES CT
JOIN TOWNS T ON T.CITYID = CT.ID
ORDER BY CT.CITY, T.TOWN

-- Istanbul'da hangi ilcede ne kadar musteri oldugunu getiren sorguyu yazýnýz

SELECT T.TOWN, COUNT(DISTINCT U.ID) NUMBER_OF_CUST FROM ADDRESS A
JOIN USERS U ON U.ID = A.USERID
JOIN CITIES CT ON CT.ID = A.CITYID
JOIN TOWNS T ON T.ID = A.TOWNID
WHERE CT.CITY = 'ÝSTANBUL'
GROUP BY T.TOWN

--2022 yýlý Mart ayýnda 20-30 yas arasý müsterilerin verdiði siparisleri listeleyiniz
SELECT U.NAMESURNAME, DATEDIFF(YEAR, U.BIRTHDATE, GETDATE()) AGE,
C.CITY, O.DATE_,O.ID ,O.TOTALPRICE
from USERS U
JOIN ORDERS O ON O.USERID = U.ID
JOIN ADDRESS A ON  A.ID= O.ADDRESSID
JOIN CITIES C ON C.ID = A.CITYID
WHERE DATEDIFF(YEAR, U.BIRTHDATE, GETDATE()) BETWEEN 20 AND 30 AND O.DATE_ BETWEEN '2022-03-01' AND '2022-03-31 23:59:59'
ORDER BY DATE_

-- Kullanýcýlarýn hangi sehirde kac adresi oldugu bilgisini veriniz
SELECT
U.NAMESURNAME, C.CITY, COUNT(A.ID) ADDRESS_NUM 
FROM USERS U
JOIN ADDRESS A ON A.USERID = U.ID
JOIN CITIES C ON C.ID = A.CITYID
GROUP BY U.NAMESURNAME, C.CITY

--ISTANBUL'DA yýlýn ilk 3 ayýnda en cok satýs yapýlan 10 ürünü getiriniz.
SELECT TOP 10
C.CITY, I.ITEMCODE, I.ITEMNAME, I.BRAND, I.CATEGORY1, I.CATEGORY2, I.CATEGORY3,
SUM(OD.AMOUNT) SUM_AMOUNT , SUM(OD.LINETOTAL) SUM_LINE_TOTAL
FROM ORDERS O
JOIN ADDRESS A ON A.ID = O.ADDRESSID
JOIN CITIES C ON C.ID = A.CITYID
JOIN ORDERDETAILS OD ON OD.ORDERID = O.ID
JOIN ITEMS I ON I.ID = OD.ITEMID
WHERE C.CITY = 'ÝSTANBUL' AND O.DATE_ BETWEEN '20220101' AND '20220401'
GROUP BY C.CITY, I.ITEMCODE, I.ITEMNAME, I.BRAND, I.CATEGORY1, I.CATEGORY2, I.CATEGORY3
ORDER BY SUM_LINE_TOTAL DESC

-- haftanýn günlerine göre ne kadar alýsveris yapýldýðýný gösteren sql sorgusu

SELECT
DATENAME(DW,O.DATE_) DAY_NAME, SUM(O.TOTALPRICE) TOTAL_PRICE,
COUNT(O.ID) ORDERS_NUM
FROM ORDERS O
GROUP BY DATENAME(DW, O.DATE_),DATEPART(DW, O.DATE_)
ORDER BY DATEPART(DW, O.DATE_)

-- SAAT aralýgýna göre ne kadar alýsveris yapýldýgý bilgisini getiren sql sorgusu
SELECT
DATEPART(HOUR,O.DATE_) HOURS , ROUND(SUM(O.TOTALPRICE),0) TOTAL_PRICE,
COUNT(O.ID) ORDERS_NUM
FROM ORDERS O
GROUP BY DATEPART(HOUR, O.DATE_)
ORDER BY 1


-- her siparis icin toplam sevketme süresini listeleyiniz.
SELECT O.ID ORDER_ID,
U.NAMESURNAME, C.CITY, O.DATE_ ORDER_DATE,
IV.DATE_ Shipment_DATE,
DATEDIFF(HOUR, O.DATE_, IV.DATE_) DATE_DIFF
FROM ORDERS O
JOIN USERS U ON U.ID = O.USERID
JOIN ADDRESS A ON A.ID = O.ADDRESSID
JOIN CITIES C ON C.ID = A.CITYID
JOIN INVOICES IV ON IV.ORDERID = O.ID
ORDER BY ORDER_ID

-- siparislerin bölgelere göre ve sehirlere göre ortalama sevketme sürelerini getiren sorguyu yazýnýz.
SELECT C.REGION,
AVG(DATEDIFF(HOUR, O.DATE_, IV.DATE_)*1.0) AVG_DATE_DIFF
FROM ORDERS O
JOIN ADDRESS A ON A.ID = O.ADDRESSID
JOIN CITIES C ON C.ID = A.CITYID
JOIN INVOICES IV ON IV.ORDERID = O.ID
GROUP BY C.REGION

SELECT C.CITY,
AVG(DATEDIFF(HOUR, O.DATE_, IV.DATE_)*1.0) AVG_DATE_DIFF
FROM ORDERS O
JOIN ADDRESS A ON A.ID = O.ADDRESSID
JOIN CITIES C ON C.ID = A.CITYID
JOIN INVOICES IV ON IV.ORDERID = O.ID
GROUP BY C.CITY


-- siparis tarihinin ayý ile fatura tarihinin ayý farklý olan siparisleri getiriniz.

SELECT 
O.ID ORDER_ID, O.DATE_ ORDER_DATE,
IV.DATE_ INVOICE_DATE,
DATENAME(MONTH, O.DATE_) ORDER_MONTH,  DATENAME(MONTH, IV.DATE_) INVOICE_MONTH
FROM ORDERS O
JOIN INVOICES IV ON IV.ORDERID = O.ID
WHERE DATEPART(MONTH, O.DATE_) != DATEPART(MONTH, IV.DATE_)
ORDER BY ORDER_DATE

-- her ay icin siparis tarihinin ayý ile fatura tarihinin ayý farklý olan siparis sayýlarýný getiriniz
SELECT 
DATENAME(MONTH, O.DATE_) ORDER_MONTH, COUNT(*) ORDER_NUMBER
FROM ORDERS O
JOIN INVOICES IV ON IV.ORDERID = O.ID
WHERE DATEPART(MONTH, O.DATE_) != DATEPART(MONTH, IV.DATE_)
GROUP BY DATENAME(MONTH, O.DATE_), DATEPART(MONTH, O.DATE_)
ORDER BY DATEPART(MONTH, O.DATE_)


-- Her bir sehirde ne kadar erkek ne kadar kadýn var sayýsýný getiren sorguyu yazýnýz.

SELECT C.CITY, U.GENDER, COUNT(U.GENDER) USER_NUMBER
FROM USERS U
JOIN ADDRESS A ON A.USERID = U.ID
JOIN CITIES C ON C.ID = A.CITYID
GROUP BY C.CITY, U.GENDER
ORDER BY C.CITY

-- 'DETERJAN TEMÝZLÝK' VE 'GIDA' kategorisindeki ürünlerin bölgelere göre yapýlan toplam satýslarýný getiriniz.

select C.REGION, I.CATEGORY1, SUM(OD.LINETOTAL) TOTAL_SALES  from ORDERDETAILS OD
JOIN ITEMS I ON OD.ITEMID = I.ID
JOIN ORDERS O ON O.ID=OD.ORDERID
JOIN ADDRESS A ON A.ID = O.ADDRESSID
JOIN CITIES C ON C.ID = A.CITYID
WHERE I.CATEGORY1 IN ('DETERJAN TEMÝZLÝK', 'GIDA')
GROUP BY REGION, I.CATEGORY1
ORDER BY C.REGION

-- Her bir ürün icin toplam ne kadarlýk satýs yapýldýgýný adet ve toplam ciro olarak getiriniz
--ayrýca her bir ürün icin en düsük, en yüksek, ortalama satýs ve mevcut fiyata göre kar-zarar hesabýný yapan sorguyu getiriniz.
SELECT *, 
ROUND(LINE_TOTAL -PRICE_IN_LIST,0) PROFIT_LOSS,
ROUND(100*(LINE_TOTAL -PRICE_IN_LIST) / PRICE_IN_LIST,0) PERCENT_PROFIT_LOSS

FROM
(
SELECT 
	I.ITEMCODE ITEMCODE, I.ITEMNAME, I.UNITPRICE, SUM(OD.AMOUNT) TOTAL_AMOUNT, SUM(OD.LINETOTAL) LINE_TOTAL,
	MIN(OD.UNITPRICE) MIN_PRICE, MAX(OD.UNITPRICE) MAX_PRICE, ROUND(AVG(OD.UNITPRICE),0) AVG_PRICE,
	SUM(OD.AMOUNT * I.UNITPRICE) PRICE_IN_LIST
from ITEMS I
JOIN ORDERDETAILS OD ON OD.ITEMID = I.ID
GROUP BY I.ITEMCODE, I.ITEMNAME, I.UNITPRICE
) T
ORDER BY PERCENT_PROFIT_LOSS DESC

