/*
kim tarafindan?
ne zaman?
Hangi bilgisayardan?
Hangi kullanici ile?
Hangi program ile?
Silinmeden/degistirilmeden onceki degerleri neydi?
Triggers kullanarak bu islemleri gerceklestiriniz
*/

CREATE TRIGGER TG_ITEMS_UPDATE_DELETE
ON ITEMS
AFTER UPDATE,DELETE
AS
BEGIN
DECLARE @INSERTEDCOUNT AS INT
DECLARE @DELETEDCOUNT AS INT
DECLARE @LOG_ACTIONTYPE AS VARCHAR(10)

SELECT @INSERTEDCOUNT = COUNT(*) FROM inserted
SELECT @DELETEDCOUNT = COUNT(*) FROM deleted

IF @INSERTEDCOUNT>0 AND @DELETEDCOUNT>0
	SET @LOG_ACTIONTYPE='UPDATE'
IF @INSERTEDCOUNT=0 AND @DELETEDCOUNT>0
	SET @LOG_ACTIONTYPE = 'DELETE'

INSERT INTO ITEMS_LOG
(ID, BRAND, ITEMCODE, ITEMNAME, CATEGORY1, CATEGORY2, CATEGORY3, UNITPRICE, 
LOG_ACTIONTYPE, LOG_DATE, LOG_USERNAME, LOG_HOSTNAME, LOG_PROGRAMNAME)

SELECT ID, BRAND, ITEMCODE,ITEMNAME, CATEGORY1,CATEGORY2,CATEGORY3,UNITPRICE,
@LOG_ACTIONTYPE,GETDATE(),SUSER_SNAME(),HOST_NAME(), PROGRAM_NAME()
FROM DELETED

END

SELECT * FROM ITEMS where ID =1
UPDATE ITEMS
SET UNITPRICE=1.5
WHERE ID=1

UPDATE ITEMS
SET UNITPRICE=1.8
WHERE ID=1

DELETE FROM ITEMS
WHERE ID=1

SELECT * FROM ITEMS_LOG